name: repo_viewer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  dartz: ^0.10.1
  dio: ^5.0.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296
  # material_floating_search_bar: ^0.3.7
  material_floating_search_bar_2: ^0.5.0
  oauth2: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.13
  sembast: ^3.4.0+6
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.6
  webview_flutter_android: ^3.8.0
  webview_flutter_wkwebview: ^3.1.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - env/
    - config/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
