name: repo_viewer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  dartz: ^0.10.1
  dio: ^5.0.1
  flash: ^2.0.5+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.2.0
  http: ^0.13.5
  material_design_icons_flutter: ^6.0.7096
  oauth2: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.13
  sembast: ^3.4.0+6
  webview_flutter: ^4.0.6
  webview_flutter_android: ^3.3.1
  webview_flutter_wkwebview: ^3.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter:
  uses-material-design: true
