// Mocks generated by Mockito 5.4.4 from annotations
// in repo_viewer/test/auth/application/auth_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:oauth2/oauth2.dart' as _i2;
import 'package:repo_viewer/auth/domain/auth_failure.dart' as _i6;
import 'package:repo_viewer/auth/infrastructure/github_authenticator.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthorizationCodeGrant_0 extends _i1.SmartFake
    implements _i2.AuthorizationCodeGrant {
  _FakeAuthorizationCodeGrant_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GithubAuthenticator].
///
/// See the documentation for Mockito's code generation for more information.
class MockGithubAuthenticator extends _i1.Mock
    implements _i4.GithubAuthenticator {
  @override
  _i5.Future<_i2.Credentials?> getSignedInCredentials() => (super.noSuchMethod(
        Invocation.method(
          #getSignedInCredentials,
          [],
        ),
        returnValue: _i5.Future<_i2.Credentials?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Credentials?>.value(),
      ) as _i5.Future<_i2.Credentials?>);

  @override
  _i5.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i2.AuthorizationCodeGrant createGrant() => (super.noSuchMethod(
        Invocation.method(
          #createGrant,
          [],
        ),
        returnValue: _FakeAuthorizationCodeGrant_0(
          this,
          Invocation.method(
            #createGrant,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeAuthorizationCodeGrant_0(
          this,
          Invocation.method(
            #createGrant,
            [],
          ),
        ),
      ) as _i2.AuthorizationCodeGrant);

  @override
  Uri getAuthorizationUrl(_i2.AuthorizationCodeGrant? grant) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthorizationUrl,
          [grant],
        ),
        returnValue: _FakeUri_1(
          this,
          Invocation.method(
            #getAuthorizationUrl,
            [grant],
          ),
        ),
        returnValueForMissingStub: _FakeUri_1(
          this,
          Invocation.method(
            #getAuthorizationUrl,
            [grant],
          ),
        ),
      ) as Uri);

  @override
  _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>> handleAuthorizationResponse(
    _i2.AuthorizationCodeGrant? grant,
    Map<String, String>? queryParams,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleAuthorizationResponse,
          [
            grant,
            queryParams,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
            _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #handleAuthorizationResponse,
            [
              grant,
              queryParams,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
                _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #handleAuthorizationResponse,
            [
              grant,
              queryParams,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>> signOut() =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
            _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
                _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>> clearCredentialsStorage() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCredentialsStorage,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
            _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #clearCredentialsStorage,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>.value(
                _FakeEither_2<_i6.AuthFailure, _i3.Unit>(
          this,
          Invocation.method(
            #clearCredentialsStorage,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AuthFailure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i6.AuthFailure, _i2.Credentials>> refresh(
          _i2.Credentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [credentials],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.AuthFailure, _i2.Credentials>>.value(
                _FakeEither_2<_i6.AuthFailure, _i2.Credentials>(
          this,
          Invocation.method(
            #refresh,
            [credentials],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.AuthFailure, _i2.Credentials>>.value(
                _FakeEither_2<_i6.AuthFailure, _i2.Credentials>(
          this,
          Invocation.method(
            #refresh,
            [credentials],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AuthFailure, _i2.Credentials>>);
}
